#!/usr/bin/env python3
import subprocess
import json
import os
import sys
import re
from collections import defaultdict
from datetime import datetime

D1_DATABASE = 'nuvio-recomendacoes'
TRIAGE_ISSUE = 192

def exec_d1(sql: str) -> list:
    """Execute D1 query and return results"""
    cmd = [
        'npx', '--yes', 'wrangler', 'd1', 'execute',
        D1_DATABASE, '--remote', '--json',
        '--command', sql
    ]

    try:
        output = subprocess.check_output(cmd, stderr=subprocess.PIPE, text=True, timeout=30)
        json_start = output.find('[')
        if json_start == -1:
            return []
        json_str = output[json_start:]
        data = json.loads(json_str)
        if isinstance(data, list) and len(data) > 0:
            return data[0].get('results', [])
        return []
    except Exception as e:
        print(f"Error: {e}", file=sys.stderr)
        return []

def main():
    print("Getting latest triage summary...", file=sys.stderr)

    # Get latest triagem entries (last 50)
    result = exec_d1('''
    SELECT padrao, versao, plataforma, ocorrencias, pessoas, estado, criado
    FROM triagem
    WHERE criado = (SELECT MAX(criado) FROM triagem)
    ORDER BY ocorrencias DESC;
    ''')

    if not result:
        print("No triage data found", file=sys.stderr)
        return 1

    # Group by version
    by_version = defaultdict(list)
    for entry in result:
        by_version[entry['versao']].append(entry)

    # Generate report
    lines = [
        "## Log Triage Report",
        "",
        f"**Updated**: {datetime.utcnow().isoformat()}Z",
        "",
        "### Pattern Summary",
        ""
    ]

    # Summarize patterns by version
    for version in sorted(by_version.keys()):
        entries = by_version[version]
        total_occurrences = sum(e['ocorrencias'] for e in entries)
        total_people = sum(e['pessoas'] for e in entries)
        unique_patterns = len(entries)

        lines.append(f"#### v{version}")
        lines.append(f"- Patterns: {unique_patterns}")
        lines.append(f"- Occurrences: {total_occurrences}")
        lines.append(f"- Affected users: {total_people}")
        lines.append("")

        # List top patterns
        for entry in sorted(entries, key=lambda x: x['ocorrencias'], reverse=True)[:5]:
            state_emoji = {
                'novo': '🆕',
                'conhecido': '📋',
                'regrediu': '🔴',
            }.get(entry['estado'], '❓')
            lines.append(f"  {state_emoji} `{entry['padrao']}` ({entry['plataforma']}) - {entry['ocorrencias']}x, {entry['pessoas']} users")

        lines.append("")

    lines.append("---")
    lines.append("Auto-generated by log triage routine")

    report = "\n".join(lines)
    print(report)
    return 0

if __name__ == '__main__':
    sys.exit(main())
